# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AkAudioInputSource_config = debug
  AkCompressorFX_config = debug
  AkDelayFX_config = debug
  AkExpanderFX_config = debug
  AkFlangerFX_config = debug
  AkGainFX_config = debug
  AkGuitarDistortionFX_config = debug
  AkHarmonizerFX_config = debug
  AkMatrixReverbFX_config = debug
  AkMemoryMgr_config = debug
  AkMeterFX_config = debug
  AkMusicEngine_config = debug
  AkOpusDecoder_config = debug
  AkParametricEQFX_config = debug
  AkPeakLimiterFX_config = debug
  AkPitchShifterFX_config = debug
  AkRecorderFX_config = debug
  AkRoomVerbFX_config = debug
  AkSilenceSource_config = debug
  AkSineSource_config = debug
  AkSoundEngine_config = debug
  AkSpatialAudio_config = debug
  AkStereoDelayFX_config = debug
  AkStreamMgr_config = debug
  AkSynthOneSource_config = debug
  AkTimeStretchFX_config = debug
  AkToneSource_config = debug
  AkTremoloFX_config = debug
  AkVorbisDecoder_config = debug
  CommunicationCentral_config = debug
endif
ifeq ($(config),profile)
  AkAudioInputSource_config = profile
  AkCompressorFX_config = profile
  AkDelayFX_config = profile
  AkExpanderFX_config = profile
  AkFlangerFX_config = profile
  AkGainFX_config = profile
  AkGuitarDistortionFX_config = profile
  AkHarmonizerFX_config = profile
  AkMatrixReverbFX_config = profile
  AkMemoryMgr_config = profile
  AkMeterFX_config = profile
  AkMusicEngine_config = profile
  AkOpusDecoder_config = profile
  AkParametricEQFX_config = profile
  AkPeakLimiterFX_config = profile
  AkPitchShifterFX_config = profile
  AkRecorderFX_config = profile
  AkRoomVerbFX_config = profile
  AkSilenceSource_config = profile
  AkSineSource_config = profile
  AkSoundEngine_config = profile
  AkSpatialAudio_config = profile
  AkStereoDelayFX_config = profile
  AkStreamMgr_config = profile
  AkSynthOneSource_config = profile
  AkTimeStretchFX_config = profile
  AkToneSource_config = profile
  AkTremoloFX_config = profile
  AkVorbisDecoder_config = profile
  CommunicationCentral_config = profile
endif
ifeq ($(config),profile_enableasserts)
  AkAudioInputSource_config = profile_enableasserts
  AkCompressorFX_config = profile_enableasserts
  AkDelayFX_config = profile_enableasserts
  AkExpanderFX_config = profile_enableasserts
  AkFlangerFX_config = profile_enableasserts
  AkGainFX_config = profile_enableasserts
  AkGuitarDistortionFX_config = profile_enableasserts
  AkHarmonizerFX_config = profile_enableasserts
  AkMatrixReverbFX_config = profile_enableasserts
  AkMemoryMgr_config = profile_enableasserts
  AkMeterFX_config = profile_enableasserts
  AkMusicEngine_config = profile_enableasserts
  AkOpusDecoder_config = profile_enableasserts
  AkParametricEQFX_config = profile_enableasserts
  AkPeakLimiterFX_config = profile_enableasserts
  AkPitchShifterFX_config = profile_enableasserts
  AkRecorderFX_config = profile_enableasserts
  AkRoomVerbFX_config = profile_enableasserts
  AkSilenceSource_config = profile_enableasserts
  AkSineSource_config = profile_enableasserts
  AkSoundEngine_config = profile_enableasserts
  AkSpatialAudio_config = profile_enableasserts
  AkStereoDelayFX_config = profile_enableasserts
  AkStreamMgr_config = profile_enableasserts
  AkSynthOneSource_config = profile_enableasserts
  AkTimeStretchFX_config = profile_enableasserts
  AkToneSource_config = profile_enableasserts
  AkTremoloFX_config = profile_enableasserts
  AkVorbisDecoder_config = profile_enableasserts
  CommunicationCentral_config = profile_enableasserts
endif
ifeq ($(config),release)
  AkAudioInputSource_config = release
  AkCompressorFX_config = release
  AkDelayFX_config = release
  AkExpanderFX_config = release
  AkFlangerFX_config = release
  AkGainFX_config = release
  AkGuitarDistortionFX_config = release
  AkHarmonizerFX_config = release
  AkMatrixReverbFX_config = release
  AkMemoryMgr_config = release
  AkMeterFX_config = release
  AkMusicEngine_config = release
  AkOpusDecoder_config = release
  AkParametricEQFX_config = release
  AkPeakLimiterFX_config = release
  AkPitchShifterFX_config = release
  AkRecorderFX_config = release
  AkRoomVerbFX_config = release
  AkSilenceSource_config = release
  AkSineSource_config = release
  AkSoundEngine_config = release
  AkSpatialAudio_config = release
  AkStereoDelayFX_config = release
  AkStreamMgr_config = release
  AkSynthOneSource_config = release
  AkTimeStretchFX_config = release
  AkToneSource_config = release
  AkTremoloFX_config = release
  AkVorbisDecoder_config = release
  CommunicationCentral_config = release
endif

PROJECTS := AkAudioInputSource AkCompressorFX AkDelayFX AkExpanderFX AkFlangerFX AkGainFX AkGuitarDistortionFX AkHarmonizerFX AkMatrixReverbFX AkMemoryMgr AkMeterFX AkMusicEngine AkOpusDecoder AkParametricEQFX AkPeakLimiterFX AkPitchShifterFX AkRecorderFX AkRoomVerbFX AkSilenceSource AkSineSource AkSoundEngine AkSpatialAudio AkStereoDelayFX AkStreamMgr AkSynthOneSource AkTimeStretchFX AkToneSource AkTremoloFX AkVorbisDecoder CommunicationCentral

.PHONY: all clean help $(PROJECTS) Communication - Proxy Opus Plugins Plugins/Effects Plugins/Sources Vorbis

all: $(PROJECTS)

Communication - Proxy: CommunicationCentral

Opus: AkOpusDecoder

Plugins: Plugins/Effects Plugins/Sources

Plugins/Effects: AkCompressorFX AkDelayFX AkExpanderFX AkFlangerFX AkGainFX AkGuitarDistortionFX AkHarmonizerFX AkMatrixReverbFX AkMeterFX AkParametricEQFX AkPeakLimiterFX AkPitchShifterFX AkRecorderFX AkRoomVerbFX AkStereoDelayFX AkTimeStretchFX AkTremoloFX

Plugins/Sources: AkAudioInputSource AkSilenceSource AkSineSource AkSynthOneSource AkToneSource

Vorbis: AkVorbisDecoder

AkAudioInputSource:
	@echo "==== Building AkAudioInputSource ($(AkAudioInputSource_config)) ===="
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkAudioInput/Sources/AudioEngineFX/Linux -f AkAudioInputSourceLinux.make config=$(AkAudioInputSource_config)

AkCompressorFX:
	@echo "==== Building AkCompressorFX ($(AkCompressorFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkCompressor/Linux -f AkCompressorFXLinux.make config=$(AkCompressorFX_config)

AkDelayFX:
	@echo "==== Building AkDelayFX ($(AkDelayFX_config)) ===="
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkDelay/Sources/AudioEngineFX/Linux -f AkDelayFXLinux.make config=$(AkDelayFX_config)

AkExpanderFX:
	@echo "==== Building AkExpanderFX ($(AkExpanderFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkExpander/Linux -f AkExpanderFXLinux.make config=$(AkExpanderFX_config)

AkFlangerFX:
	@echo "==== Building AkFlangerFX ($(AkFlangerFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkFlanger/Linux -f AkFlangerFXLinux.make config=$(AkFlangerFX_config)

AkGainFX:
	@echo "==== Building AkGainFX ($(AkGainFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkGain/Linux -f AkGainFXLinux.make config=$(AkGainFX_config)

AkGuitarDistortionFX:
	@echo "==== Building AkGuitarDistortionFX ($(AkGuitarDistortionFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkGuitarDistortion/Linux -f AkGuitarDistortionFXLinux.make config=$(AkGuitarDistortionFX_config)

AkHarmonizerFX:
	@echo "==== Building AkHarmonizerFX ($(AkHarmonizerFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkHarmonizer/Linux -f AkHarmonizerFXLinux.make config=$(AkHarmonizerFX_config)

AkMatrixReverbFX:
	@echo "==== Building AkMatrixReverbFX ($(AkMatrixReverbFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkFDNReverb/Linux -f AkMatrixReverbFXLinux.make config=$(AkMatrixReverbFX_config)

AkMemoryMgr:
	@echo "==== Building AkMemoryMgr ($(AkMemoryMgr_config)) ===="
	@${MAKE} --no-print-directory -C AkMemoryMgr/Linux -f AkMemoryMgrLinux.make config=$(AkMemoryMgr_config)

AkMeterFX:
	@echo "==== Building AkMeterFX ($(AkMeterFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkMeter/Linux -f AkMeterFXLinux.make config=$(AkMeterFX_config)

AkMusicEngine:
	@echo "==== Building AkMusicEngine ($(AkMusicEngine_config)) ===="
	@${MAKE} --no-print-directory -C AkMusicEngine/Linux -f AkMusicEngineLinux.make config=$(AkMusicEngine_config)

AkOpusDecoder:
	@echo "==== Building AkOpusDecoder ($(AkOpusDecoder_config)) ===="
	@${MAKE} --no-print-directory -C Codecs/AkOpusDecoder/Linux -f AkOpusDecoderLinux.make config=$(AkOpusDecoder_config)

AkParametricEQFX:
	@echo "==== Building AkParametricEQFX ($(AkParametricEQFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkParametricEQ/Linux -f AkParametricEQFXLinux.make config=$(AkParametricEQFX_config)

AkPeakLimiterFX:
	@echo "==== Building AkPeakLimiterFX ($(AkPeakLimiterFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkPeakLimiter/Linux -f AkPeakLimiterFXLinux.make config=$(AkPeakLimiterFX_config)

AkPitchShifterFX:
	@echo "==== Building AkPitchShifterFX ($(AkPitchShifterFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkPitchShifter/Linux -f AkPitchShifterFXLinux.make config=$(AkPitchShifterFX_config)

AkRecorderFX:
	@echo "==== Building AkRecorderFX ($(AkRecorderFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkRecorder/Linux -f AkRecorderFXLinux.make config=$(AkRecorderFX_config)

AkRoomVerbFX:
	@echo "==== Building AkRoomVerbFX ($(AkRoomVerbFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkRoomVerb/Linux -f AkRoomVerbFXLinux.make config=$(AkRoomVerbFX_config)

AkSilenceSource:
	@echo "==== Building AkSilenceSource ($(AkSilenceSource_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Sources/AkSilenceSource/Linux -f AkSilenceSourceLinux.make config=$(AkSilenceSource_config)

AkSineSource:
	@echo "==== Building AkSineSource ($(AkSineSource_config)) ===="
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkSineTone/Sources/AudioEngineFX/Linux -f AkSineSourceLinux.make config=$(AkSineSource_config)

AkSoundEngine:
	@echo "==== Building AkSoundEngine ($(AkSoundEngine_config)) ===="
	@${MAKE} --no-print-directory -C AkAudiolib/Linux -f AkSoundEngineLinux.make config=$(AkSoundEngine_config)

AkSpatialAudio:
	@echo "==== Building AkSpatialAudio ($(AkSpatialAudio_config)) ===="
	@${MAKE} --no-print-directory -C ../SpatialAudio/Linux -f AkSpatialAudioLinux.make config=$(AkSpatialAudio_config)

AkStereoDelayFX:
	@echo "==== Building AkStereoDelayFX ($(AkStereoDelayFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkStereoDelay/Linux -f AkStereoDelayFXLinux.make config=$(AkStereoDelayFX_config)

AkStreamMgr:
	@echo "==== Building AkStreamMgr ($(AkStreamMgr_config)) ===="
	@${MAKE} --no-print-directory -C ../StreamManager/Linux -f AkStreamMgr.make config=$(AkStreamMgr_config)

AkSynthOneSource:
	@echo "==== Building AkSynthOneSource ($(AkSynthOneSource_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Sources/AkSynthOne/Linux -f AkSynthOneSourceLinux.make config=$(AkSynthOneSource_config)

AkTimeStretchFX:
	@echo "==== Building AkTimeStretchFX ($(AkTimeStretchFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkTimeStretch/Linux -f AkTimeStretchFXLinux.make config=$(AkTimeStretchFX_config)

AkToneSource:
	@echo "==== Building AkToneSource ($(AkToneSource_config)) ===="
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkToneGenerator/Sources/AudioEngineFX/Linux -f AkToneSourceLinux.make config=$(AkToneSource_config)

AkTremoloFX:
	@echo "==== Building AkTremoloFX ($(AkTremoloFX_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/Effects/AkTremolo/Linux -f AkTremoloFXLinux.make config=$(AkTremoloFX_config)

AkVorbisDecoder:
	@echo "==== Building AkVorbisDecoder ($(AkVorbisDecoder_config)) ===="
	@${MAKE} --no-print-directory -C Codecs/AkVorbisDecoder/Linux -f AkVorbisDecoderLinux.make config=$(AkVorbisDecoder_config)

CommunicationCentral:
	@echo "==== Building CommunicationCentral ($(CommunicationCentral_config)) ===="
	@${MAKE} --no-print-directory -C Communication/Remote/Linux -f CommunicationCentralLinux.make config=$(CommunicationCentral_config)

clean:
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkAudioInput/Sources/AudioEngineFX/Linux -f AkAudioInputSourceLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkCompressor/Linux -f AkCompressorFXLinux.make clean
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkDelay/Sources/AudioEngineFX/Linux -f AkDelayFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkExpander/Linux -f AkExpanderFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkFlanger/Linux -f AkFlangerFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkGain/Linux -f AkGainFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkGuitarDistortion/Linux -f AkGuitarDistortionFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkHarmonizer/Linux -f AkHarmonizerFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkFDNReverb/Linux -f AkMatrixReverbFXLinux.make clean
	@${MAKE} --no-print-directory -C AkMemoryMgr/Linux -f AkMemoryMgrLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkMeter/Linux -f AkMeterFXLinux.make clean
	@${MAKE} --no-print-directory -C AkMusicEngine/Linux -f AkMusicEngineLinux.make clean
	@${MAKE} --no-print-directory -C Codecs/AkOpusDecoder/Linux -f AkOpusDecoderLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkParametricEQ/Linux -f AkParametricEQFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkPeakLimiter/Linux -f AkPeakLimiterFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkPitchShifter/Linux -f AkPitchShifterFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkRecorder/Linux -f AkRecorderFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkRoomVerb/Linux -f AkRoomVerbFXLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Sources/AkSilenceSource/Linux -f AkSilenceSourceLinux.make clean
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkSineTone/Sources/AudioEngineFX/Linux -f AkSineSourceLinux.make clean
	@${MAKE} --no-print-directory -C AkAudiolib/Linux -f AkSoundEngineLinux.make clean
	@${MAKE} --no-print-directory -C ../SpatialAudio/Linux -f AkSpatialAudioLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkStereoDelay/Linux -f AkStereoDelayFXLinux.make clean
	@${MAKE} --no-print-directory -C ../StreamManager/Linux -f AkStreamMgr.make clean
	@${MAKE} --no-print-directory -C Plugins/Sources/AkSynthOne/Linux -f AkSynthOneSourceLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkTimeStretch/Linux -f AkTimeStretchFXLinux.make clean
	@${MAKE} --no-print-directory -C ../../samples/Plugins/AkToneGenerator/Sources/AudioEngineFX/Linux -f AkToneSourceLinux.make clean
	@${MAKE} --no-print-directory -C Plugins/Effects/AkTremolo/Linux -f AkTremoloFXLinux.make clean
	@${MAKE} --no-print-directory -C Codecs/AkVorbisDecoder/Linux -f AkVorbisDecoderLinux.make clean
	@${MAKE} --no-print-directory -C Communication/Remote/Linux -f CommunicationCentralLinux.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  profile"
	@echo "  profile_enableasserts"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AkAudioInputSource"
	@echo "   AkCompressorFX"
	@echo "   AkDelayFX"
	@echo "   AkExpanderFX"
	@echo "   AkFlangerFX"
	@echo "   AkGainFX"
	@echo "   AkGuitarDistortionFX"
	@echo "   AkHarmonizerFX"
	@echo "   AkMatrixReverbFX"
	@echo "   AkMemoryMgr"
	@echo "   AkMeterFX"
	@echo "   AkMusicEngine"
	@echo "   AkOpusDecoder"
	@echo "   AkParametricEQFX"
	@echo "   AkPeakLimiterFX"
	@echo "   AkPitchShifterFX"
	@echo "   AkRecorderFX"
	@echo "   AkRoomVerbFX"
	@echo "   AkSilenceSource"
	@echo "   AkSineSource"
	@echo "   AkSoundEngine"
	@echo "   AkSpatialAudio"
	@echo "   AkStereoDelayFX"
	@echo "   AkStreamMgr"
	@echo "   AkSynthOneSource"
	@echo "   AkTimeStretchFX"
	@echo "   AkToneSource"
	@echo "   AkTremoloFX"
	@echo "   AkVorbisDecoder"
	@echo "   CommunicationCentral"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"