# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

CC = clang
CXX = clang++
AR = ar

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  PREMAKE4_BUILDTARGET_BASENAME = AkSpatialAudio
  TARGETDIR = ../../../Linux_$(AK_LINUX_ARCH)/Debug/lib
  TARGET = $(TARGETDIR)/libAkSpatialAudio.a
  OBJDIR = ../../../Linux_$(AK_LINUX_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  DEFINES += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES += -I../../../include -I. -I../Common -I../../SoundEngine/AkAudiolib/Common -I../../SoundEngine/AkAudiolib/SoftwarePipeline -I../../SoundEngine/Plugins/Effects/Common -I../../SoundEngine/AkAudiolib/Linux -I../POSIX -I../../SoundEngine/AkAudiolib/POSIX
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++11 -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),profile)
  PREMAKE4_BUILDTARGET_BASENAME = AkSpatialAudio
  TARGETDIR = ../../../Linux_$(AK_LINUX_ARCH)/Profile/lib
  TARGET = $(TARGETDIR)/libAkSpatialAudio.a
  OBJDIR = ../../../Linux_$(AK_LINUX_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  DEFINES += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES += -I../../../include -I. -I../Common -I../../SoundEngine/AkAudiolib/Common -I../../SoundEngine/AkAudiolib/SoftwarePipeline -I../../SoundEngine/Plugins/Effects/Common -I../../SoundEngine/AkAudiolib/Linux -I../POSIX -I../../SoundEngine/AkAudiolib/POSIX
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++11 -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),profile_enableasserts)
  PREMAKE4_BUILDTARGET_BASENAME = AkSpatialAudio
  TARGETDIR = ../../../Linux_$(AK_LINUX_ARCH)/Profile_EnableAsserts/lib
  TARGET = $(TARGETDIR)/libAkSpatialAudio.a
  OBJDIR = ../../../Linux_$(AK_LINUX_ARCH)/Profile_EnableAsserts/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  DEFINES += -DNDEBUG -DAK_ENABLE_ASSERTS -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES += -I../../../include -I. -I../Common -I../../SoundEngine/AkAudiolib/Common -I../../SoundEngine/AkAudiolib/SoftwarePipeline -I../../SoundEngine/Plugins/Effects/Common -I../../SoundEngine/AkAudiolib/Linux -I../POSIX -I../../SoundEngine/AkAudiolib/POSIX
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++11 -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release)
  PREMAKE4_BUILDTARGET_BASENAME = AkSpatialAudio
  TARGETDIR = ../../../Linux_$(AK_LINUX_ARCH)/Release/lib
  TARGET = $(TARGETDIR)/libAkSpatialAudio.a
  OBJDIR = ../../../Linux_$(AK_LINUX_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  DEFINES += -DAK_OPTIMIZED -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES += -I../../../include -I. -I../Common -I../../SoundEngine/AkAudiolib/Common -I../../SoundEngine/AkAudiolib/SoftwarePipeline -I../../SoundEngine/Plugins/Effects/Common -I../../SoundEngine/AkAudiolib/Linux -I../POSIX -I../../SoundEngine/AkAudiolib/POSIX
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++11 -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS)
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/AkAcousticPortal.o \
	$(OBJDIR)/AkAcousticRoom.o \
	$(OBJDIR)/AkDiffractionEdge.o \
	$(OBJDIR)/AkDiffractionPath.o \
	$(OBJDIR)/AkGeometrySet.o \
	$(OBJDIR)/AkImageSource.o \
	$(OBJDIR)/AkReflectInstance.o \
	$(OBJDIR)/AkScene.o \
	$(OBJDIR)/AkSoundGeometry.o \
	$(OBJDIR)/AkSpatialAudio.o \
	$(OBJDIR)/AkSpatialAudioCompts.o \
	$(OBJDIR)/AkSpatialAudioTasks.o \
	$(OBJDIR)/AkStochasticPath.o \
	$(OBJDIR)/AkStochasticReflectionEngine.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (sh.exe,$(SHELL))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking AkSpatialAudio
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) if not exist $(subst /,\\,$(TARGETDIR)) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) if not exist $(subst /,\\,$(OBJDIR)) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning AkSpatialAudio
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/AkAcousticPortal.o: ../Common/AkAcousticPortal.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkAcousticRoom.o: ../Common/AkAcousticRoom.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkDiffractionEdge.o: ../Common/AkDiffractionEdge.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkDiffractionPath.o: ../Common/AkDiffractionPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkGeometrySet.o: ../Common/AkGeometrySet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkImageSource.o: ../Common/AkImageSource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkReflectInstance.o: ../Common/AkReflectInstance.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkScene.o: ../Common/AkScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkSoundGeometry.o: ../Common/AkSoundGeometry.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkSpatialAudio.o: ../Common/AkSpatialAudio.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkSpatialAudioCompts.o: ../Common/AkSpatialAudioCompts.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkSpatialAudioTasks.o: ../Common/AkSpatialAudioTasks.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkStochasticPath.o: ../Common/AkStochasticPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AkStochasticReflectionEngine.o: ../Common/AkStochasticReflectionEngine.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif