# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AkStreamMgr_config = debug
endif
ifeq ($(config),profile)
  AkStreamMgr_config = profile
endif
ifeq ($(config),profile_enableasserts)
  AkStreamMgr_config = profile_enableasserts
endif
ifeq ($(config),release)
  AkStreamMgr_config = release
endif

PROJECTS := AkStreamMgr

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AkStreamMgr:
	@echo "==== Building AkStreamMgr ($(AkStreamMgr_config)) ===="
	@${MAKE} --no-print-directory -C . -f AkStreamMgr.make config=$(AkStreamMgr_config)

clean:
	@${MAKE} --no-print-directory -C . -f AkStreamMgr.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  profile"
	@echo "  profile_enableasserts"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AkStreamMgr"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"